# Generated by Django 5.1.3 on 2024-12-03 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_mailing_owner_message_owner_recipient_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("view_all_mailings", "Может просматривать все рассылки"),
                    ("disable_mailing", "Может отключать рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("view_all_messages", "Может просматривать все сообщения")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [("view_all_recipients", "Может просматривать всех получателей")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
